authapp/urls.py
from django.urls import path

from authapp import views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('edit/', authapp.edit, name='edit'),
    path('register/', authapp.register, name='register'),
    path('verify/<email>/<activation_key>/', authapp.verify, name='verify'),

]

geekshop/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.contrib import admin
from mainapp.views import index
from mainapp.views import contact

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='authapp')),
    path('contact/', contact, name='contact'),
    path('basket', include('basketapp.urls', namespace='basketapp')),
    path('orders', include('ordersapp.urls', namespace='ordersapp')),
    path('', include('social_django.urls', namespace='social')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path, include
from mainapp.views import products

app_name = 'products'

urlpatterns = [
    path('', products, name='products'),
    path('<int:pk>/', products, name='category'),
]

ordersapp/urls.py
from django.urls import path
from ordersapp import views as ordersapp

app_name = 'ordersapp'

#в соответствии со списком статусов
urlpatterns = [
    path('', ordersapp.OrderListView.as_view(), name='list'),
    path('create/', ordersapp.OrderCreateView.as_view(), name='create'),
    path('update/<pk>/', ordersapp.OrderUpdateView.as_view(), name='update'),
    path('read/<pk>/', ordersapp.OrderDetailView.as_view(), name='read'),
    path('delete/<pk>/', ordersapp.OrderDeleteView.as_view(), name='delete'),
    path('complete/<pk>/', ordersapp.complete, name='complete'),
]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name='Название')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'категория(ю)'
        verbose_name_plural = 'Категории'

    def delete(self, *args, **kwargs):
        self.is_active = False
        self.save()


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='products_img', blank=True, null=True)
    short_desc = models.CharField(max_length=255, blank=True)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(default=0)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.name} <> {self.category.name}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'Продукты'

mainapp/views.py
import json
from datetime import datetime

from django.conf import settings
from django.shortcuts import render

from mainapp.models import Product, ProductCategory


def index(request):

    products_list = Product.objects.all()[:4]
    context = {
        'title': 'Магазин',
        'products': products_list,
        'date': datetime.now()
    }
    return render(request, 'mainapp/index.html', context)


with open(f'{settings.BASE_DIR}/mainapp/fixtures/products.json') as file:
    json_product = json.load(file)


def products(request, pk=None):
    links_menu = ProductCategory.objects.all()
    context = {
        'title': 'Каталог',
        'links_menu': links_menu,
        'products': json_product
    }
    return render(request, 'mainapp/products.html', context)


def contact(request):
    with open(f'{settings.BASE_DIR}/mainapp/fixtures/contacts.json') as f:
        json_contact = json.load(f)
    context = {
        'title': 'Контакты',
        'contacts': json_contact
    }
    return render(request, 'mainapp/contact.html', context)

mainapp/templates/mainapp/includes/inc_categories_menu.html
<div class="links clearfix">
    <ul class="links-menu">
    <li><a href="{% url 'products:products' %}" class="{% if request.resolver_match.url_name == item.href %}active{% endif %}">Все</a></li>
        {% for item in links_menu %}
            <li><a href="{% url 'products:category' item.pk %}" class="{% if request.resolver_match.kwargs.pk == item.pk %}active{% endif %}">{{ item.name }}</a></li>
        {% endfor %}
    </ul>
</div>

mainapp/templates/mainapp/includes/inc_main_menu.html
<a href="{% url 'index' %}" class="logo"></a>
<ul class="menu">
    <li><a href="{% url 'index' %}"
           class="{% if request.resolver_match.url_name == 'index' %}active{% endif %}">домой</a></li>
    <li><a href="{% url 'products:products' %}"
           class="{% if request.resolver_match.namespace == 'products' %}active{% endif %}">продукты</a></li>

        {% if user.is_authenticated %}
            <li><a href="{% url 'authapp:edit' %}">{% if user.first_name %}{{ user.first_name }}{% else %}Пользователь{% endif %}</a></li>
            <li><a href="{% url 'ordersapp:list' %}">Заказы</a></li>
            <li><a href="{% url 'authapp:logout' %}">Выйти</a></li>
        {% else %}
            <li><a href="{% url 'authapp:register' %}">Регистрация</a></li>
            <li><a href="{% url 'authapp:login' %}">Войти</a></li>
        {% endif %}


    <li><a href="{% url 'contact' %}" class="{% if request.resolver_match.url_name == 'contact' %}active{% endif %}">контакты</a>
    </li>
</ul>
<a href="#" class="search"></a>
<a href="#" class="basket"></a>